### ISSUE TITLE
[Feature Request] Video Player Controls

### ISSUE THREAD

**Issue by bugger23** [DatL4g/Mimasu#1]
Please add swipe gestures to your video player. Swiping vertically on the left side of the screen would adjust the brightness. On the right side it would adjust the volume. Swiping horizontally back and forth would skip through the video. Here is an example: https://www.dropbox.com/scl/fi/1cz1wy0m9o7xhao7e7sy0/Screenrecorder-2024-09-08-13-18-55-439.mp4?rlkey=x9219gs4ij1g7s5ofvv77ewyb&st=3iw636r2&dl=0

**Comment by DatL4g** [comment]
Video player enhancements will come with the new app, probably with a more YouTube-ish control style.

BTW you can just drag-n-drop videos here on GitHub, you don't have to upload them to Dropbox etc

**Comment by bugger23** [comment]
Hey, whats up with the new Player Features, AS you said that this will come in the next Release?

**Comment by DatL4g** [comment]
The features are implemented but the app isn't available yet.
You can "watch" the repository if you want to receive a notification on release.
